import { SECTION_LABELS } from './prdSystemPrompt.js'

// ─── Word (.docx) export ───────────────────────────────────────────────

export async function exportPrdAsDocx(prd, title = 'Product Requirements Document') {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType } = await import('docx')

  const borderNone = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }
  const cellBorder = {
    top: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' },
    left: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' },
    right: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' },
  }

  function h(text, level = HeadingLevel.HEADING_1) {
    return new Paragraph({ text, heading: level, spacing: { before: 300, after: 100 } })
  }

  function p(text, bold = false) {
    return new Paragraph({
      children: [new TextRun({ text: text || '', bold, size: 22 })],
      spacing: { after: 80 },
    })
  }

  function labelValue(label, value) {
    return new Paragraph({
      children: [
        new TextRun({ text: `${label}: `, bold: true, size: 22 }),
        new TextRun({ text: value || '', size: 22 }),
      ],
      spacing: { after: 80 },
    })
  }

  function tableRow(cells, isHeader = false) {
    return new TableRow({
      children: cells.map((text) =>
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: text || '', bold: isHeader, size: 20 })] })],
          borders: cellBorder,
        })
      ),
    })
  }

  const children = [
    new Paragraph({ text: title, heading: HeadingLevel.TITLE, spacing: { after: 200 } }),
    new Paragraph({ text: `Generated by AI PM Co-Pilot · ${new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}`, spacing: { after: 400 } }),

    h('1. Executive Summary'),
    labelValue('Vision', prd.executive_summary?.vision),
    labelValue('Problem', prd.executive_summary?.problem),
    labelValue('Solution', prd.executive_summary?.solution),
    labelValue('Target User', prd.executive_summary?.target_user),
    labelValue('One-liner', prd.executive_summary?.one_liner),

    h('2. Goals & Success Metrics'),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        tableRow(['Metric', 'Description', 'Target', 'Measurement Method'], true),
        ...(prd.goals_and_metrics || []).map((g) =>
          tableRow([g.metric, g.description, g.target, g.measurement_method])
        ),
      ],
    }),

    h('3. User Personas'),
    ...(prd.user_personas || []).flatMap((p, i) => [
      new Paragraph({ text: `Persona ${i + 1}: ${p.role}`, heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 80 } }),
      labelValue('Context', p.context),
      labelValue('Pain', p.pain),
      labelValue('Goal', p.goal),
      labelValue('Usage Pattern', p.usage_pattern),
    ]),

    h('4. User Stories'),
    ...(prd.user_stories || []).flatMap((s) => [
      new Paragraph({
        children: [new TextRun({ text: `${s.id}: As a ${s.as_a}, I want ${s.i_want}, so that ${s.so_that}`, bold: true, size: 22 })],
        spacing: { before: 160, after: 60 },
      }),
      new Paragraph({ children: [new TextRun({ text: 'Acceptance Criteria:', bold: true, size: 20 })], spacing: { after: 40 } }),
      ...(s.acceptance_criteria || []).map((ac) =>
        new Paragraph({ text: `• ${ac}`, indent: { left: 360 }, spacing: { after: 40 } })
      ),
    ]),

    h('5. Functional Requirements'),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        tableRow(['ID', 'Feature', 'Description', 'Priority', 'Notes'], true),
        ...(prd.functional_requirements || []).map((r) =>
          tableRow([r.id, r.feature, r.description, r.priority, r.notes])
        ),
      ],
    }),

    h('6. Technical Requirements'),
    ...(prd.technical_requirements || []).map((r) =>
      new Paragraph({
        children: [
          new TextRun({ text: `[${r.category}] `, bold: true, size: 22 }),
          new TextRun({ text: r.requirement, size: 22 }),
          new TextRun({ text: ` — ${r.rationale}`, italics: true, size: 20, color: '666666' }),
        ],
        spacing: { after: 80 },
      })
    ),

    h('7. Release Plan'),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        tableRow(['Phase', 'Scope', 'Timeline', 'Success Gate'], true),
        ...(prd.release_plan || []).map((r) =>
          tableRow([r.phase, r.scope, r.timeline, r.success_gate])
        ),
      ],
    }),

    h('8. RAID Log'),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        tableRow(['Type', 'Item', 'Impact', 'Mitigation'], true),
        ...(prd.raid_log || []).map((r) =>
          tableRow([r.type, r.item, r.impact, r.mitigation])
        ),
      ],
    }),
  ]

  const doc = new Document({ sections: [{ children }] })
  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}_PRD.docx`
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Markdown copy ─────────────────────────────────────────────────────

export function prdToMarkdown(prd) {
  const es = prd.executive_summary || {}
  const lines = [
    `# ${es.one_liner || 'Product Requirements Document'}`,
    '',
    `> **Vision:** ${es.vision || ''}`,
    '',
    `**Problem:** ${es.problem || ''}`,
    `**Solution:** ${es.solution || ''}`,
    `**Target User:** ${es.target_user || ''}`,
    '',
    '## Goals & Success Metrics',
    '',
    '| Metric | Description | Target | Measurement |',
    '|--------|-------------|--------|-------------|',
    ...(prd.goals_and_metrics || []).map((g) =>
      `| ${g.metric} | ${g.description} | ${g.target} | ${g.measurement_method} |`
    ),
    '',
    '## User Personas',
    '',
    ...(prd.user_personas || []).flatMap((p) => [
      `### ${p.role}`,
      `**Context:** ${p.context}`,
      `**Pain:** ${p.pain}`,
      `**Goal:** ${p.goal}`,
      `**Usage:** ${p.usage_pattern}`,
      '',
    ]),
    '## User Stories',
    '',
    ...(prd.user_stories || []).flatMap((s) => [
      `**${s.id}:** As a ${s.as_a}, I want ${s.i_want}, so that ${s.so_that}`,
      '',
      'Acceptance Criteria:',
      ...(s.acceptance_criteria || []).map((ac) => `- ${ac}`),
      '',
    ]),
    '## Functional Requirements',
    '',
    '| ID | Feature | Description | Priority | Notes |',
    '|----|---------|-------------|----------|-------|',
    ...(prd.functional_requirements || []).map((r) =>
      `| ${r.id} | ${r.feature} | ${r.description} | ${r.priority} | ${r.notes} |`
    ),
    '',
    '## Technical Requirements',
    '',
    ...(prd.technical_requirements || []).map((r) =>
      `- **[${r.category}]** ${r.requirement} — *${r.rationale}*`
    ),
    '',
    '## Release Plan',
    '',
    '| Phase | Scope | Timeline | Success Gate |',
    '|-------|-------|----------|--------------|',
    ...(prd.release_plan || []).map((r) =>
      `| ${r.phase} | ${r.scope} | ${r.timeline} | ${r.success_gate} |`
    ),
    '',
    '## RAID Log',
    '',
    '| Type | Item | Impact | Mitigation |',
    '|------|------|--------|------------|',
    ...(prd.raid_log || []).map((r) =>
      `| ${r.type} | ${r.item} | ${r.impact} | ${r.mitigation} |`
    ),
    '',
    `---`,
    `*Generated by AI PM Co-Pilot · ${new Date().toLocaleDateString()}*`,
  ]

  return lines.join('\n')
}

// ─── User Stories CSV export ───────────────────────────────────────────

export function exportUserStoriesCSV(userStories, filename = 'user_stories.csv') {
  const headers = ['ID', 'As a', 'I want', 'So that', 'Acceptance Criteria']
  const rows = (userStories || []).map((s) => [
    s.id,
    s.as_a,
    s.i_want,
    s.so_that,
    (s.acceptance_criteria || []).join(' | '),
  ])

  const csv = [headers, ...rows]
    .map((row) => row.map((cell) => `"${String(cell || '').replace(/"/g, '""')}"`).join(','))
    .join('\n')

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Handoff content formatter ─────────────────────────────────────────

export function formatHandoffContent(prd) {
  const stories = (prd.user_stories || [])
    .map((s) => {
      const ac = (s.acceptance_criteria || []).map((c, i) => `  ${i + 1}. ${c}`).join('\n')
      return `${s.id}: As a ${s.as_a}, I want ${s.i_want}, so that ${s.so_that}\nAcceptance Criteria:\n${ac}`
    })
    .join('\n\n')

  const reqs = (prd.functional_requirements || [])
    .filter((r) => r.priority === 'Must Have' || r.priority === 'Should Have')
    .map((r) => `${r.id}: ${r.feature} (${r.priority}) — ${r.description}`)
    .join('\n')

  return `## User Stories\n\n${stories}\n\n## Functional Requirements\n\n${reqs}`
}
